### PR TITLE
Update job_template_fmriprep.txt

### PR DESCRIPTION
**Pull request by duettwe**
Looks like it's the job_template that needs an update.

### CODE REVIEW

**Comment by baxpr** [comment]
You can't change this because it's in use (I think, right?)

Why are we seeing this DATA/SUBJECT difference when both old and new are using FS6 as input?

**Comment by duettwe** [comment]
Hmm, I'm not sure why that was changed to SUBJECT from DATA. It looks like I created the new fmriprep yaml with SUBJECT already there. Pretty sure I copied from the old one though, but that doesn't match up.

**Comment by baxpr** [comment]
Which freesurfer is running on the specific xnat project? Maybe it's not fs6

**Comment by duettwe** [comment]
Oh, I see what happened. I copied the fmriprep_v20.2.3 yaml from the fmriprep_v20.2.1 yaml in the dax_processors_test_zone. Looks like that one is using SUBJECT for some reason. I think this was just a copying mistake and I can update the test one to use DATA, like the existing one in the running_processors branch.

> Which freesurfer is running on the specific xnat project? Maybe it's not fs6
freesurfer_dev_v2

**Comment by baxpr** [comment]
Ok. You are probably going to have to make a new yaml+job template combo specifically for freesurfer_dev_v2, because it does store outputs in a SUBJECT resource not a DATA resource.

**Comment by baxpr** [comment]
I would suggest tagging it like fmriprep-fsdev2 or something

**Comment by duettwe** [comment]
Do we want both an fmriprep_v20.2.3 (using DATA) and fmriprep-fsdev2_v20.2.3 (using SUBJECT and new job_template)?

**Comment by baxpr** [comment]
Just get the one you need right now working, for starters

**Pull request closed without merging**
