### PR TITLE
Job template for BIDS-Apps

### PR DESCRIPTION
**Pull request by praitayini**
Hi 

Please can you review the job template for BIDS App. 
Implementation details:
1. It uses the XnatToBids function in DAX for the BIDS Conversion. 
2. It creates the PDF from the OUTLOG. I used the package fpdf. This should be added the requirements in DAX. 
3. For fmriprep, it uses the preexisting Freesurfer output 

Testing:
Tested 2 BIDSApp - fmriprep and mriqc for sessions 108768, 109072, 109112  in ZALD_TTS. The processors file I used for this test is in https://github.com/VUIIS/BIDSApp_DAX_Support/tree/master/dax_processors

### CODE REVIEW

**Comment by KarthikMasi** [comment]
Making outlogs as pdf makes it less accessible on a terminal. Performing 'grep' for collective log files is also ruled out thus. Is there a reason why we need OUTLOG as PDF?

**Comment by baxpr** [comment]
Haha, forgot to actually look at it.

Need to have some recent updates that are in job_template.txt

- Needs this line
`#SBATCH --account=${job_rungroup}`

- Do not echo session IDs

- Why is there freesurfer-specific stuff in the job template?

**Comment by baxpr** [comment]
@KarthikMasi It has to produce some kind of PDF. As a general solution, we put the outlog there because otherwise we have to make it specific to each BIDS app.

**Comment by baxpr** [comment]
The outlog is copied to the PDF, it's also in the usual place as OUTLOG resource.

**Comment by baxpr** [comment]
@praitayini if this is specific to some apps (the freesurfer stuff) it should have a correspondingly specific filename. What's that part of the script doing?

**Comment by praitayini** [comment]
>     * Why is there freesurfer-specific stuff in the job template?

We wanted to use the existing freesurfer output in fmriprep. For that I had to copy the freesurfer output into fmriprep output. I assumed in BIDS Apps processor file, only in the case of fmriprep the input ftype will be "DIRJ" because it will use assessor resources (https://github.com/VUIIS/BIDSApp_DAX_Support/blob/master/dax_processors/test_fmriprep_v1.5.9_processor_ZALD.yaml).  In other cases (mriqc) the ftype would "FILE" (https://github.com/VUIIS/BIDSApp_DAX_Support/blob/master/dax_processors/mriqc_v0_processor_ZALD.yaml). So, only when ftype = DIRJ the job template will copy the freesurfer output into fmriprep output.

I'm open to suggestions on doing it another way

**Comment by baxpr** [comment]
Well, I don't like to assume that DIRJ always indicates freesurfer - that's really fragile. And, this setup is only compatible with mriqc or fmriprep, not any other bids apps, right?

I don't really see the full picture yet. But it seems like the "right now" solution might be to name this file `job_template_fmriprep.txt` and let it be purpose-specific.

Then, make a generic bids app one `job_template_bids_app.txt` that doesn't do any fancy gymnastics and will work with mriqc and whatever else.

Is that sensible/doable?

**Comment by praitayini** [comment]
> Well, I don't like to assume that DIRJ always indicates freesurfer - that's really fragile. And, this setup is only compatible with mriqc or fmriprep, not any other bids apps, right?
> 
> I don't really see the full picture yet. But it seems like the "right now" solution might be to name this file `job_template_fmriprep.txt` and let it be purpose-specific.
> 
> Then, make a generic bids app one `job_template_bids_app.txt` that doesn't do any fancy gymnastics and will work with mriqc and whatever else.
> 
> Is that sensible/doable?

I agree it is fragile. I couldn't think of another way to do it.  This setup/job template works for both mriqc and fmriprep. 

I can rename it to fmriprep. 

I can make a new file with those lines removed for the generic bids app template.

**Comment by baxpr** [comment]
Works for me if it works for you.

**Comment by praitayini** [comment]
> Works for me if it works for you.

done. thank you for taking the time!

**Comment by baxpr** [comment]
@praitayini I think it should still check for a present PDF file. Why didn't the haspdf logic work? That all happens after the PDF has been created.

**Comment by baxpr** [comment]
... Oh I see. You put it DSTDIR straight away. Ok, how about adding a quick check that there is one PDF file and it's not zero size?

**Comment by praitayini** [comment]
> ... Oh I see. You put it DSTDIR straight away. Ok, how about adding a quick check that there is one PDF file and it's not zero size?


> ... Oh I see. You put it DSTDIR straight away. Ok, how about adding a quick check that there is one PDF file and it's not zero size?
add these lines
+[ -f $PDFFILE ] && haspdf=1 || echo "PDF does not exist"
+[ -s $PDFFILE ] && echo "PDF not empty" || echo "PDF is empty" && errors=1

**Comment by praitayini** [comment]
> ... Oh I see. You put it DSTDIR straight away. Ok, how about adding a quick check that there is one PDF file and it's not zero size?

Okay, add these two lines
[ -f $PDFFILE ] && haspdf=1 || echo "PDF does not exist"
[ -s $PDFFILE ] && echo "PDF not empty" || echo "PDF is empty" && errors=1

**Comment by baxpr** [comment]
@praitayini Thanks!

**Comment by praitayini** [comment]
@baxpr Can I merge this? I have tested this with the new yaml https://github.com/VUIIS/yaml_processors/pull/71

**Comment by baxpr** [comment]
Oh, here it is - go for it!

**Comment by baxpr** [comment]
... Actually, maybe just merge the one file that you need. No need to add a file that isn't in use.

**Comment by praitayini** [comment]
> ... Actually, maybe just merge the one file that you need. No need to add a file that isn't in use.

done

**Review by baxpr — APPROVED** [review]

**Pull request merged**
