### PR TITLE
Move proper quoting to the standard job template

### PR DESCRIPTION
**Pull request by baxpr**
We still need to quote the URLs here.

### CODE REVIEW

**Comment by baxpr** [comment]
I tested this on one assessor in PS_NEURO and it worked fine - that was the one with difficult characters in the URLs.

**Comment by baxpr** [comment]
Argh, I got my wires crossed again. No this is not needed if the URL is correctly URL-encoded in the first place as fixed in https://github.com/VUIIS/dax/pull/326

**Comment by baxpr** [comment]
I'm wrong, again. It is needed

**Comment by duettwe** [comment]
Why do these have to be escaped and not the other single/double quotes?

**Comment by baxpr** [comment]
These have to be escaped because they have to pass literally into the eval command later.

Actually I think we should remove the quotes around JSESSIONID as well, let me do that

**Comment by baxpr** [comment]
Also I think the "else" section is borken - won't the single quotes here prevent substitution of the col3 value? I haven't tested this (and, not sure we ever use it in practice)

```
        CMD="curl -D - -s -b JSESSIONID=$SESSID '\"$col3\"?format=zip&structure=simplified' -o $INDIR/${col1}.zip"
```

**Comment by baxpr** [comment]
That might have fixed it. Not sure how to test

**Comment by baxpr** [comment]
@bud42 can you please review this? I'm going to need it for http://xnatbug.vandyxnat.org/bugzilla/show_bug.cgi?id=1906 but I'm worried it'll break something

**Comment by bud42** [comment]
This looks good to me, but I'm going to test it to be sure.

**Comment by baxpr** [comment]
Thanks. In particular, do you know a way to test that third case here?
https://github.com/VUIIS/dax_templates/pull/10#issuecomment-862643952

**Review by bud42 — APPROVED** [review]

**Pull request merged**
